[tool.pylint.messages_control]
disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods",
    "line-too-long",
    "redefined-outer-name",
    "possibly-used-before-assignment",
    "unused-argument",
    "dangerous-default-value",
    "broad-exception-caught",
    "too-many-statements",
    "too-many-arguments",
    "too-many-locals",
    "no-else-return",
    "use-dict-literal",
    "unspecified-encoding",
    "too-many-branches",
    "inconsistent-return-statements",
    "bare-except",
    "pointless-string-statement",
    "too-many-function-args",
    "wrong-import-position",
    "duplicate-code",
    "ungrouped-imports",
    "protected-access",
    "trailing-newlines",
    "check-added-large-files"
]

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true


[tool.isort]
multi_line_output = 3
length_sort = true
