{
 "title": "Dashboard",
 "description": "Some queries for RAG performance monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Response Time Panel",
   "type": "timeseries",
   "description": "This query shows the response time for each conversation within the selected time range",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  response_time\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Relevance Distribution Panel",
   "type": "piechart",
   "description": "This query counts the number of conversations for each relevance category within the selected time range",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  relevance,\n  COUNT(*) as count\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY relevance"
    }
   ]
  },
  {
   "title": "Model Usage Panel",
   "type": "barchart",
   "description": "This query counts the number of times each model was used within the selected time range",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  model_used,\n  COUNT(*) as count\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY model_used"
    }
   ]
  },
  {
   "title": "Global Token Usage Panel",
   "type": "timeseries",
   "description": "This query shows the average token usage over time, grouped by automatically calculated interval",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  AVG(total_tokens) AS avg_tokens\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Token Usage per model Panel",
   "type": "bargauge",
   "description": "This query shows the average token usage per model within the selected time range",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  model_used,\n  AVG(total_tokens) AS avg_tokens\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OpenAI Cost Panel",
   "type": "timeseries",
   "description": "This query shows the total OpenAI cost over time, grouped  automatically calculated interval",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  SUM(openai_cost) AS total_cost\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\n  AND openai_cost > 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Recent Conversations Panel",
   "type": "table",
   "description": "This query retrieves the 5 most recent conversations within the selected time range",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  question,\n  answer,\n  relevance\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Feedback Statistics Panel",
   "type": "piechart",
   "description": "This query calculates the total number of positive and negative feedback within the selected time range",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN feedback = 0 THEN 1 ELSE 0 END) as Very_BAD,\n  SUM(CASE WHEN feedback = 1  THEN 1 ELSE 0 END) as BAD,\n  SUM(CASE WHEN feedback = 2 THEN 1 ELSE 0 END) as ACCEPTABLE,\n  SUM(CASE WHEN feedback = 3 THEN 1 ELSE 0 END) as GOOD,\n  SUM(CASE WHEN feedback = 4 THEN 1 ELSE 0 END) as Excellent\nFROM feedbacks\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  }
 ]
}